### ISSUE TITLE
Configurable format of printed records with eclog tool

### ISSUE THREAD

**Issue by eperott** [Ericsson/ecaudit#102]
The eclog tool which is used to extract and print Chronicle logs will print one entry per line using a hard coded format. We should investigate ways to make the print format configurable, much the same way as we have for the Slf4jLogger backend.

Ideally the format definition for eclog should be the same as the one used by the Slf4jLogger backend. Still I think we should make this configuration independent of the audit.yaml file, but this is open for discussion.

**Comment by etedpet** [comment]
A review comment to #101 that is worth considering when implementing this feature:
"Might be something for future work, but how do you as a user of this tool differentiate between client ip & coordinator ip since both can be optional?

I.e. if we have CLIENT_IP but not CLIENT_PORT or COORDINATOR_IP. Or if we only have COORDINATOR_IP."

Should we (in the default format) use tags for the values to make sure different fields are not mixed up? (when reading ecLog output)

**Comment by etedpet** [comment]
Do we need an Integration Test covering this functionality? The question came up during a #101 review comment...
