### ISSUE TITLE
Add support for system timestamp in log message - align with C* 4.0

### ISSUE THREAD

**Issue by eperott** [Ericsson/ecaudit#27]
In Cassandra 4.0 audit log implementation the system timestamp is embedded into the audit log message.

We should add this to ecAudit to close feature gap.

In C* 4.0, documentation claim "unix timestamp", but implementation is using System.currentTimeMillis().

**Comment by eperott** [comment]
Valid point. In order to maintain backwards compatibility with current format, I believe we should address #55 before we fix this ticket. With a configurable formatter in place, this ticket could extend things further such that the timestamp field could be formatted as a human readable date or a ms timestamp. This way we could remain backwards compatible also when resolving this ticket.

**Comment by etedpet** [comment]
There are actually 2 (potentially different) timestamps that might be interesting to log:

1. The **request timestamp**, the system time Cassandra processes the request.
2. The **record timestamp**, the unique timestamp of a records in the database. 

Note that not all requests have record timestamps (only modification statements updating records in the database). So for example a select statement does not have a record timestamp. The record timestamp can also be configured by the client and can be set to any point in time.

Both timestamps might be interesting to audit log, but this issue will focus on the request timestamp (system timestamp). 

Note also that it is possible to log a timestamp via LOGBack. But that timestamp will not be as precise as the request timestamp, since LOGBack handles/prints the logs asynchronously.
