### ISSUE TITLE
Exception encountered during startup

### ISSUE THREAD

**Issue by phanirajl** [Ericsson/ecaudit#64]
ERROR [main] 2019-02-16 00:25:25,789 CassandraDaemon.java:708 - Exception encountered during startup
java.lang.NoSuchMethodError: org.apache.cassandra.cql3.statements.ParsedStatement.prepare()Lorg/apache/cassandra/cql3/statements/ParsedStatement$Prepared;
	at com.ericsson.bss.cassandra.ecaudit.auth.WhitelistDataAccess.prepare(WhitelistDataAccess.java:273) ~[ecaudit_c3.0.11-2.1.0-SNAPSHOT.jar:na]
	at com.ericsson.bss.cassandra.ecaudit.auth.WhitelistDataAccess.setup(WhitelistDataAccess.java:91) ~[ecaudit_c3.0.11-2.1.0-SNAPSHOT.jar:na]
	at com.ericsson.bss.cassandra.ecaudit.filter.role.RoleAuditFilter.setup(RoleAuditFilter.java:59) ~[ecaudit_c3.0.11-2.1.0-SNAPSHOT.jar:na]
	at com.ericsson.bss.cassandra.ecaudit.facade.DefaultAuditor.setup(DefaultAuditor.java:45) ~[ecaudit_c3.0.11-2.1.0-SNAPSHOT.jar:na]
	at com.ericsson.bss.cassandra.ecaudit.AuditAdapter.setup(AuditAdapter.java:82) ~[ecaudit_c3.0.11-2.1.0-SNAPSHOT.jar:na]
	at com.ericsson.bss.cassandra.ecaudit.auth.AuditPasswordAuthenticator.setup(AuditPasswordAuthenticator.java:87) ~[ecaudit_c3.0.11-2.1.0-SNAPSHOT.jar:na]
	at org.apache.cassandra.service.StorageService.doAuthSetup(StorageService.java:1091) ~[apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.StorageService.finishJoiningRing(StorageService.java:1081) ~[apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1003) ~[apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:682) ~[apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:613) ~[apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:379) [apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:602) [apache-cassandra-3.11.2.jar:3.11.2]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:691) [apache-cassandra-3.11.2.jar:3.11.2]

**Comment by laxmikant99** [comment]
It looks like you are using an incompatible version of ecaudit  (ecaudit_c3.0.11-2.1.0-SNAPSHOT.jar:) with cassandra 3.11.2 Use the correct tag of ecaudit, see below:


Flavor | Versions | Compiled With
-- | -- | --
ecaudit_c3.11 | 0.22 -> | Cassandra 3.11.3
ecaudit_c3.11 | 0.1 -> 0.21 | Cassandra 3.11.2

**Comment by eperott** [comment]
Like Laxmikant says, you're using an incompatible falvor of ecAudit. The plug-in comes in several different flavors in order to support different versions of Cassandra. Check out the CONTRIBUTING document for details.

If you want to build ecAudit for Cassandra 3.11.2 your best bet is to checkout and build the master branch of ecAudit. It should be noted though that the master branch is currently targeting Cassandra 3.11.3, so can't guarantee that things will work without modification.

**Comment by eperott** [comment]
The default branch in this repo is "release/c3.0.11" on order to simplify development for several different Cassandra versions. You should be able to verify that this is your current branch with "git status" at the command line.

Try to use ecAudit from the master branch. Do "git checkout master" at the command line and build again.

Things work in Intellij simply because maven resolves all needed dependencies, including Cassandra, for the unit tests to run.

To use ecAudit in an actual Cassandra deployment you may want to use the officially released artifacts from Maven Central: https://search.maven.org/artifact/com.ericsson.bss.cassandra.ecaudit/ecaudit_c3.11/2.0.0/jar

Sorry if I'm describing the obvious.

**Comment by phanirajl** [comment]
Sorry for bothering you ..!I have checked out master branch and tried to build.Test are failing for the same error.PFA screenshot
<img width="1331" alt="screen shot 2019-02-19 at 1 55 03 pm" src="https://user-images.githubusercontent.com/18603562/53050404-196a4880-344e-11e9-94c6-f1bc16941354.png">

**Comment by eperott** [comment]
No worries. :-)

I believe you get this in Intellij because it is out of sync with the repo which sometimes happens when you switch branch in git. Try to right-click the pom file, and select Maven->Reimport. Then run the tests again.

In any case you should be able to execute the tests at the command line by "mvn verify"

**Comment by phanirajl** [comment]
still no luck.... :)
[ERROR]   TestAuditAdapter.com.ericsson.bss.cassandra.ecaudit.TestAuditAdapter » NoClassDefFound
[ERROR]   TestAuditAuthorizer.com.ericsson.bss.cassandra.ecaudit.auth.TestAuditAuthorizer » ExceptionInInitializer
[ERROR]   TestAuditRoleManager.testAlterRole:147 » NoClassDefFound Could not initialize ...
[ERROR]   TestAuditRoleManager.testCreateRole:134 » NoClassDefFound Could not initialize...
[ERROR]   TestAuditRoleManager.testDropRole:187 » NoClassDefFound Could not initialize c...
[ERROR]   TestAuditRoleManager.testGrantRole:163 » NoClassDefFound Could not initialize ...
[ERROR]   TestAuditRoleManager.testRevokeRole:175 » NoClassDefFound Could not initialize...
[ERROR]   TestAuditWhitelistManager.com.ericsson.bss.cassandra.ecaudit.auth.TestAuditWhitelistManager » NoClassDefFound
[ERROR]   TestPermissionChecker.normalUserCanAlterOtherOptionMap:93->givenNormalUser:140 » NoClassDefFound
[ERROR]   TestPermissionChecker.normalUserCanChangeOwnPassword:83->givenNormalUser:140 » NoClassDefFound
[ERROR]   TestPermissionChecker.normalUserCanNotAlterOtherAllAttributes:103->givenNormalUser:140 » NoClassDefFound
[ERROR]   TestPermissionChecker.superUserCanChangeAllAttributes:73->givenSuperUser:123 » NoClassDefFound
[ERROR]   TestPermissionChecker.trustedUserCanAlterOtherAllAttributes:114->givenTrustedUser:130 » NoClassDefFound
[INFO] 
[ERROR] Tests run: 162, Failures: 0, Errors: 13, Skipped: 3
[INFO]

**Comment by eperott** [comment]
Hmm, I'm still thinking this is because Intellij is out of sync with the project on disk and its dependencies somehow. Can you elaborate a bit on how you setup your environment and run the tests?

Also, what happens if you check the types on the mentioned lines. For instance, at line 140 in TestPermisssionChecker class you should see a reference to the AuthenticatedUser type. Will Intellij resolve the dependency for you if you hold ctrl and click the class name?

**Comment by phanirajl** [comment]
I have just clone the master repo and open in Intellj--enable the auto imports. 
<img width="1664" alt="screen shot 2019-02-19 at 11 33 44 pm" src="https://user-images.githubusercontent.com/18603562/53074136-d7b5be00-349e-11e9-9ba7-fdfb12236418.png">

**Comment by phanirajl** [comment]
<img width="1674" alt="screen shot 2019-02-19 at 11 36 53 pm" src="https://user-images.githubusercontent.com/18603562/53074326-4b57cb00-349f-11e9-9939-a15f612912a4.png">

**Comment by eperott** [comment]
Hmm, I tried myself on a fresh clone. I'm not able to reproduce your specific error, but there are a couple of limitations to be aware of:
- clone repo
- checkout master branch
- open Intellij in that dir
- enable auto-import

At this point it should be possible to run tests, but within Intellij it is not possible to mix unit tests and integration tests in one go - this has to do with the integration-tests which are starting up an embedded Cassandra in the process which has its own static initialization procedure. I should probably look into breaking this up in different modules. But as of now, either select the unit tests under src->test->java->com.ericsson.bss.cassandra.ecaudit->* and run them. If you still face issues, should at least be able to select and run specific unit test class, please try and see if that works.

Regarding integration tests, simplest way to run these is to run one test class at a time.

Finally, at the command line you should be able to test everything in one go with "mvn verify", please try and let me know.
